### ISSUE TITLE
SLiCE model

### ISSUE THREAD

**Issue by Shreyas-Bhat** [BUPT-GAMMA/OpenHGNN#118]
## ❓ Questions and Help
Hello! Thank you for the wonderful library. 

 I needed some help in running the code for the SLiCE model on any dataset for link prediction that you might have tested on. Can you please help me with the steps of doing the same?

**Comment by VoidHaruhi** [comment]
Hi @Shreyas-Bhat , I'm the contributor of SLiCE model. Since this model is too complex, I failed to reproduce the performance in the original paper. I recommend you refer to the repository of the author. I'm testing how to run SLiCE on OpenHGNN, but I cannot ensure the performance.
By the way, I cannot reproduce the results even using the original code. You may ask the author. I guess she use the embedding from CompGCN as the initial embedding, then do pretraining and finetuning.

**Comment by Shreyas-Bhat** [comment]
Hi @VoidHaruhi Thank you for the reply!
I am facing this error- Can you help me out here?
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/56354373/180129400-c76a921b-77cb-4ea9-b710-67770a0cee30.png">

**Comment by lazishu2000** [comment]
This issue has been resolved; for specific details, see:
https://github.com/BUPT-GAMMA/OpenHGNN/commit/01275b74590425f6afa6ea36004ee18df6f7b7de
