### ISSUE TITLE
Help needed: Wanted behavior of Experiment.specific_trainerflow.get method and task/trainerflow registration

### ISSUE THREAD

**Issue by Carayolj** [BUPT-GAMMA/OpenHGNN#145]
Hi, 
I am trying to create a new trainer flow, as well as a new task. I am struggling a bit and have a few questions:
When I register them with `@register_flow(str_flow)` and `@register_task(str_task)`, must `str_task `and `str_flow `be identical?  
Because as my flow is not specific to a model, it is not in the `specific_trainerflow `dictionnary defined in the `Experiment` class. So the line 92 in experiment.py( `trainerflow = self.specific_trainerflow.get(self.config.model, self.config.task)` )   returns the key of the task as the trainerflow_key. Is this the wanted behavior? 

Thanks!

**Comment by Zhanghyi** [comment]
In our system, all trainerflows are registered in SUPPORTED_FLOWS. The trainerflow can be either determined by model_name or task_name. If the model can fit in node_classification or link_prediction, which are two major tasks in gnn, it's ok not to create a new flow for this model. Otherwise, we create a new trainerflow for this model and specify the mapping in specific_trainerflow.
Since your flow is not specific to a model, I will assume that the flow and the task match each other and you are going to apply existing models to a new scenario. I suggest that you make them identical. 
Another more flexible option is that you use openhgnn as a package and only import the model you need in your code.

**Comment by Carayolj** [comment]
I see, thanks for your answer
